export const ru = {
  goToContent: 'Перейти к содержимому',
  studyMeta: 'Изучено 18 из 42',
  brand: 'Memly',
  home: 'Главная',
  library: 'Моя библиотека',
  folders: 'Папки',
  progress: 'Прогресс',
  search: 'Найти набор',
  create: 'Создать набор',
  settings: 'Настройки',
  greeting: 'Привет, Максим!',
  subtitle: 'Продолжим учиться?',
  continueLabel: 'Продолжить изучение',
  continue: 'Продолжить',
  cards: 'Карточки',
  learn: 'Заучивание',
  test: 'Тест',
  match: 'Подбор',
  cardsHint: 'Просматривайте и листайте',
  learnHint: 'Повторяйте с интервалами',
  testHint: 'Проверьте свои знания',
  matchHint: 'Соединяйте пары',
  chooseMode: 'Выберите режим обучения',
  yourDecks: 'Ваши наборы',
  allDecks: 'Все наборы',
  week: 'На этой неделе',
  allStats: 'Смотреть всю статистику',
  days: 'дней подряд',
  studied: 'изучено карточек',
  completed: 'завершённых набора',
  time: 'время обучения',
  timeValue: '2 ч 18 мин',
  prototype: 'Прототип',
  tagline: 'Учитесь в своём ритме',
  prototypeHint: 'Демонстрационные данные. Изменения доступны до обновления страницы.',
  help: 'О прототипе',
  close: 'Закрыть',
  openMenu: 'Открыть меню',
  closeMenu: 'Закрыть меню',
  profile: 'Открыть профиль',
  account: 'Максим Воронцов',
  accountHint: 'Ваше пространство для обучения',
  back: 'Назад',
  toLibrary: 'В библиотеку',
  all: 'Все',
  favorites: 'Избранное',
  mine: 'Мои наборы',
  libraryHint: 'Всё, что вы хотите запомнить, в одном месте.',
  recent: 'Недавние',
  alphabetical: 'По названию',
  sort: 'Сортировка',
  empty: 'Пока ничего не нашлось',
  emptyHint: 'Попробуйте другой запрос или создайте свой набор.',
  resetSearch: 'Сбросить поиск',
  deckMenu: 'Действия с набором',
  edit: 'Редактировать',
  favorite: 'В избранное',
  unfavorite: 'Убрать из избранного',
  saved: 'Добавлено в избранное',
  unsaved: 'Удалено из избранного',
  openDeck: 'Открыть набор',
  foldersHint: 'Немного порядка — больше пространства для знаний.',
  newFolder: 'Новая папка',
  folderName: 'Название папки',
  folderPlaceholder: 'Например, подготовка к экзамену',
  createFolder: 'Создать папку',
  cancel: 'Отмена',
  folderEmpty: 'В этой папке пока нет наборов.',
  progressHint: 'Маленькие шаги складываются в большой результат.',
  thisWeek: 'Эта неделя',
  thisMonth: 'Этот месяц',
  activity: 'Активность обучения',
  activityHint: 'Каждая карточка — шаг вперёд',
  dailyGoal: 'Цель на сегодня',
  goalHint: 'Ещё 4 карточки, и цель достигнута',
  goalMonthHint: 'Отличный месяц для новых знаний',
  deckProgress: 'Прогресс по наборам',
  keepGoing: 'Продолжить обучение',
  weeklyGoal: 'Вы на верном пути',
  encouragement:
    'Пять дней подряд вы находите время для себя и новых знаний. Продолжайте в том же ритме.',
  cardsNoun: 'карточек',
  sampleCards: 'Примеры карточек',
  terms: 'Термины в наборе',
  term: 'Термин',
  definition: 'Определение',
  private: 'Только для меня',
  public: 'Для всех',
  demoContent: 'В прототипе показана небольшая часть набора.',
  author: 'Максим',
  flip: 'Нажмите, чтобы перевернуть',
  flipAria: 'Перевернуть карточку',
  previous: 'Предыдущая карточка',
  next: 'Следующая карточка',
  flipHint: 'Пробел — переворот · стрелки — переход',
  again: 'Повторить',
  know: 'Знаю',
  learning: 'Ещё учу',
  nextCard: 'Следующая карточка',
  studyHint: 'Без спешки. Одна карточка за другой.',
  chooseAnswer: 'Выберите перевод',
  selectedAnswer: 'Ответ выбран',
  selectedHint: 'Так будет выглядеть обратная связь во время обучения.',
  question: 'Вопрос',
  testHintLong: 'Выберите один ответ на каждый вопрос.',
  finishTest: 'Завершить тест',
  resultTitle: 'Отличный старт!',
  resultHint: 'Это пример экрана результатов. Проверка знаний появится в полной версии.',
  exampleResult: 'Пример результата',
  restart: 'Попробовать ещё',
  matchTitle: 'Найдите пары',
  matchHintLong: 'Выберите термин, а затем его перевод.',
  matchFinished: 'Все пары найдены!',
  matchFinishedHint: 'Новые знания уже чуть ближе.',
  pairs: 'пары',
  demoSession: 'Демонстрация режима',
  changeMode: 'Сменить режим',
  createHint: 'Соберите знания, к которым хочется возвращаться.',
  editTitle: 'Редактирование набора',
  deckName: 'Название набора',
  deckPlaceholder: 'Например, английский для путешествий',
  description: 'Описание',
  descriptionPlaceholder: 'О чём этот набор?',
  visibility: 'Кто может видеть набор',
  termLanguage: 'Язык терминов',
  definitionLanguage: 'Язык определений',
  russian: 'Русский',
  english: 'Английский',
  addCard: 'Добавить карточку',
  removeCard: 'Удалить карточку',
  saveDeck: 'Сохранить набор',
  enterTerm: 'Введите термин',
  enterDefinition: 'Введите определение',
  validation: 'Укажите название и заполните хотя бы две карточки.',
  savedDeck: 'Набор сохранён в текущем просмотре',
  savedFolder: 'Папка создана в текущем просмотре',
  profileSettings: 'Профиль',
  name: 'Имя',
  email: 'Электронная почта',
  saveChanges: 'Сохранить изменения',
  settingsSaved: 'Настройки сохранены в текущем просмотре',
  appearance: 'Оформление',
  lightTheme: 'Светлая',
  darkTheme: 'Тёмная',
  themeHint: 'Выберите комфортный для себя фон.',
  notifications: 'Напоминания',
  notificationsHint: 'Мягкое напоминание о времени для учёбы.',
  reminder: 'Напоминать об обучении',
  profileHint: 'Сделайте Memly немного больше своим.',
  helpTitle: 'Знакомьтесь, Memly',
  helpText:
    'Это интерактивный макет приложения. Открывайте наборы, переворачивайте карточки, попробуйте режимы обучения и создайте свой набор. Данные и результаты здесь демонстрационные, изменения сбрасываются при обновлении страницы.',
  gotIt: 'Понятно, посмотрим!',
} as const;

export function countLabel(count: number, forms: readonly [string, string, string]): string {
  const rest = count % 100;
  const last = count % 10;
  const form =
    rest >= 11 && rest <= 14
      ? forms[2]
      : last === 1
        ? forms[0]
        : last >= 2 && last <= 4
          ? forms[1]
          : forms[2];
  return `${count} ${form}`;
}
export const cardCount = (count: number): string =>
  countLabel(count, ['карточка', 'карточки', 'карточек']);
export const deckCount = (count: number): string =>
  countLabel(count, ['набор', 'набора', 'наборов']);

export const bulkImportText = {
  open: 'Добавить списком',
  title: 'Добавить карточки списком',
  hint: 'Одна строка — одна карточка. Проверьте результат перед добавлением.',
  separator: 'Разделитель слова и перевода',
  space: 'Пробел',
  tab: 'Табуляция',
  semicolon: 'Точка с запятой',
  separatorHints: {
    space: 'Разделяем по первому пробелу. Для словосочетаний используйте табуляцию.',
    tab: 'Разделяем по первой табуляции. Можно вставить два столбца из таблицы.',
    semicolon: 'Разделяем по первой точке с запятой: Take your time;Не торопись.',
  },
  input: 'Вставьте список',
  placeholder: 'Apple Яблоко\nQiwi Киви\nCherry Вишня',
  preview: 'Предпросмотр',
  previewLimit: 'Показаны первые 500 строк. Сократите список перед добавлением.',
  term: 'Слово',
  definition: 'Перевод',
  empty: 'Вставьте список слева — здесь появятся будущие карточки.',
  appendHint:
    'Карточки добавятся к текущему набору. Заполненные строки останутся. Затем сохраните набор.',
  notReady: 'Проверьте список перед добавлением',
  issues: {
    missingPair: 'Нужны слово и перевод, разделённые выбранным символом.',
    termTooLong: 'Слово длиннее 2000 символов.',
    definitionTooLong: 'Перевод длиннее 5000 символов.',
  },
  lines: (count: number) => countLabel(count, ['строка', 'строки', 'строк']),
  capacity: (count: number) => `Можно добавить ещё: ${cardCount(count)}. Лимит набора — 500.`,
  limit: (count: number) => `Превышен лимит набора. Можно добавить ещё: ${cardCount(count)}.`,
  invalid: (count: number) => `Исправьте строки с ошибками (${count}), чтобы добавить весь список.`,
  ready: (count: number) => `Готово к добавлению: ${cardCount(count)}`,
  add: (count: number) => `Добавить ${countLabel(count, ['карточку', 'карточки', 'карточек'])}`,
  added: (count: number) =>
    `Добавлено: ${cardCount(count)}. Сохраните набор, чтобы записать изменения.`,
} as const;
